### ISSUE TITLE
Why include an hyperfine module?

### ISSUE THREAD

**Issue by Ryton** [arturo-lang/package-ideas#1]
Couldn't you just call it externally, or even from within a script w execute?

```$ hyperfine ./somescript.art ```
>Benchmark 1: ./somescript.art
>  Time (mean ± σ):      22.3 ms ±   2.2 ms    [User: 17.6 ms, System: 4.7 ms]
>  Range (min … max):    18.5 ms …  34.0 ms    128 runs

```$ ./hyperfine.art   ; containing shebang + print execute "hyperfine somescript.art -i"```

> Benchmark 1: somescript..art
> Time (mean ± σ):     147.3 ms ±  10.9 ms    [User: 0.6 ms, System: 29.3 ms]
> Range (min … max):   114.7 ms … 164.1 ms    20 runs
>  Warning: Ignoring non-zero exit code.

Or is that not platform independent enough? (and there is a warning)

**Comment by Ryton** [comment]
(and plenty of overhead)  => might be usefull after all :-)

**Comment by drkameleon** [comment]
Well, it's the same idea: "why can't we do it better?" haha

I've personally used Hyperfine *a lot* and think it's an amazing tool, but nothing that we can't simply replicate in Arturo (I was talking to this earlier to @RickBarretto, that's how the idea came to me) and do it even better. 

Basically, it's not that we cannot simply wrap the tool, but:

- if you wrap the tool, we have an extra dependency ("install this"), which is something I'm generally not fond of, unless totally necessary
- it will be a good case to showcase Arturo packages - every package/software written in Arturo *is* (see: as something relatively easy to implement but still very useful - also, given the amount of stars Hyperfine has, let's imagine that we can make something native that competes... Let's not forget Ruby on Rails: at times, the star product that makes a language popular is not even the language itself 😉 )
